#pragma once

namespace RE
{
	enum RenderTargetMode : std::uint32_t
	{
		RENDER_TARGET_NONE = static_cast<std::underlying_type_t<RenderTargetMode>>(-1),

		RENDER_TARGET_FRAMEBUFFER = 0x0,
		RENDER_TARGET_FRAMEBUFFER_COUNT = 0x1,

		RENDER_TARGET_MAIN = 0x1,
		RENDER_TARGET_MAIN_COPY = 0x2,
		RENDER_TARGET_MAIN_SAVE_RES = 0x3,
		RENDER_TARGET_SSR_PREPASS = 0x4,
		RENDER_TARGET_SSR = 0x5,
		RENDER_TARGET_SSR_BLURRED0 = 0x6,
		RENDER_TARGET_SSR_BLURRED1 = 0x7,
		RENDER_TARGET_SSR_DEPTH = 0x8,
		RENDER_TARGET_SSR_BLEND = 0x9,
		RENDER_TARGET_WATER_DISPLACEMENT = 0xA,
		RENDER_TARGET_WATER_DISPLACEMENT_SWAP = 0xB,
		RENDER_TARGET_WATER_REFLECTIONS = 0xC,
		RENDER_TARGET_WATER_REFRACTION = 0xD,
		RENDER_TARGET_REFRACTION_NORMALS = 0xE,
		RENDER_TARGET_MENUBG = 0xF,
		RENDER_TARGET_VATS_MASK = 0xF,
		RENDER_TARGET_FACE_CUSTOMIZATION_DIFFUSE = 0x10,
		RENDER_TARGET_FACE_CUSTOMIZATION_NORMALS = 0x11,
		RENDER_TARGET_FACE_CUSTOMIZATION_SMOOTHSPEC = 0x12,
		RENDER_TARGET_LOCAL_MAP = 0x13,
		RENDER_TARGET_COMPANION_LOCAL_MAP = 0x14,
		RENDER_TARGET_COMPANION_LOCAL_MAP_NORM = 0x15,
		RENDER_TARGET_FOG_OF_WAR = 0x16,
		RENDER_TARGET_COMPANION_FOG_OF_WAR = 0x17,
		RENDER_TARGET_HUDGLASS = 0x18,
		RENDER_TARGET_HUDGLASS_SWAP = 0x19,
		RENDER_TARGET_GB_ALBEDO_SPEC = 0x1A,	//GBuffer 0
		RENDER_TARGET_GB_NORMAL = 0x1B,			//GBuffer 1
		RENDER_TARGET_GB_NORMAL_COPY = 0x1C,	//GBuffer 2
		RENDER_TARGET_GB_ENVMAP = 0x1D,			//GBuffer 3
		RENDER_TARGET_GB_AMBIENT_MAT = 0x1E,	//GBuffer 4
		RENDER_TARGET_GB_EMIT = 0x1F,			//GBuffer 5
		RENDER_TARGET_GB_MOTION_VECTORS = 0x20,	//GBuffer ?
		RENDER_TARGET_DFLIGHT = 0x21,
		RENDER_TARGET_DFSPECULAR = 0x22,
		RENDER_TARGET_DFLIGHT_TILED = 0x23,
		RENDER_TARGET_DFSPECULAR_TILED = 0x24,
		RENDER_TARGET_AO = 0x25,
		RENDER_TARGET_AO_SWAP_0 = 0x26,
		RENDER_TARGET_AO_2X = 0x27,
		RENDER_TARGET_SAO_CAMERAZ = 0x28,
		RENDER_TARGET_SAO_CAMERAZ_MIP_LEVEL_0 = 0x29,
		RENDER_TARGET_SAO_CAMERAZ_MIP_LEVEL_1 = 0x2A,
		RENDER_TARGET_SAO_CAMERAZ_MIP_LEVEL_2 = 0x2B,
		RENDER_TARGET_SAO_CAMERAZ_MIP_LEVEL_3 = 0x2C,
		RENDER_TARGET_SAO_CAMERAZ_MIP_LEVEL_4 = 0x2D,
		RENDER_TARGET_SAO_CAMERAZ_MIP_LEVEL_5 = 0x2E,
		RENDER_TARGET_SAO_CAMERAZ_MIP_LEVEL_6 = 0x2F,
		RENDER_TARGET_SAO_CAMERAZ_MIP_LEVEL_7 = 0x30,
		RENDER_TARGET_SAO_CAMERAZ_MIP_LEVEL_8 = 0x31,
		RENDER_TARGET_SAO_CAMERAZ_MIP_LEVEL_9 = 0x32,
		RENDER_TARGET_SAO_CAMERAZ_MIP_LEVEL_10 = 0x33,
		RENDER_TARGET_SAO_RAW_AO = 0x34,
		RENDER_TARGET_SAO_RAW_AO_2 = 0x35,
		RENDER_TARGET_SAO_TEMP_BLUR = 0x36,
		RENDER_TARGET_SAO_RAW_AO_2X = 0x37,
		RENDER_TARGET_SAO_RAW_AO_2_2X = 0x38,
		RENDER_TARGET_SAO_TEMP_BLUR_2X = 0x39,
		RENDER_TARGET_TEMPORAL_AA_ACCUMULATION_1 = 0x3A,
		RENDER_TARGET_TEMPORAL_AA_ACCUMULATION_2 = 0x3B,
		RENDER_TARGET_PIPBOY = 0x3C,
		RENDER_TARGET_PIPBOY_SWAP = 0x3D,
		RENDER_TARGET_MENU_SCREEN_FULLSIZE = 0x3E,
		RENDER_TARGET_MENU_SCREEN_FULLSIZE_SWAP = 0x3F,
		RENDER_TARGET_MENU_TEXT = 0x40,
		RENDER_TARGET_LENSFLAREVIS = 0x41,
		RENDER_TARGET_GETHIT_BUFFER = 0x42,
		RENDER_TARGET_BLURFULL_BUFFER = 0x43,
		RENDER_TARGET_HDR_BLURSWAP = 0x44,
		RENDER_TARGET_HDR_BLOOM = 0x45,
		RENDER_TARGET_HDR_DOWNSAMPLE0 = 0x46,
		RENDER_TARGET_HDR_DOWNSAMPLE1 = 0x47,
		RENDER_TARGET_HDR_DOWNSAMPLE2 = 0x48,
		RENDER_TARGET_HDR_DOWNSAMPLE3 = 0x49,
		RENDER_TARGET_HDR_DOWNSAMPLE4 = 0x4A,
		RENDER_TARGET_HDR_DOWNSAMPLE5 = 0x4B,
		RENDER_TARGET_HDR_DOWNSAMPLE6 = 0x4C,
		RENDER_TARGET_HDR_DOWNSAMPLE7 = 0x4D,
		RENDER_TARGET_HDR_DOWNSAMPLE8 = 0x4E,
		RENDER_TARGET_HDR_DOWNSAMPLE9 = 0x4F,
		RENDER_TARGET_HDR_DOWNSAMPLE10 = 0x50,
		RENDER_TARGET_HDR_DOWNSAMPLE11 = 0x51,
		RENDER_TARGET_HDR_DOWNSAMPLE12 = 0x52,
		RENDER_TARGET_HDR_DOWNSAMPLE13 = 0x53,
		RENDER_TARGET_DOF_1 = 0x54,
		RENDER_TARGET_DOF_2 = 0x55,
		RENDER_TARGET_RAIN_OCCLUSIONMAP = 0x56,
		RENDER_TARGET_EDITOR_TERRAIN_TEXTURE_GENERATION = 0x57,
		RENDER_TARGET_EDITOR_TERRAIN_TEXTURE_GENERATION_FINAL = 0x58,
		RENDER_TARGET_EDITOR_MAP_MAKER = 0x59,
		RENDER_TARGET_EDITOR_MAP_MAKER_SWAP = 0x5A,
		RENDER_TARGET_GODRAYS_PHASE_LUT = 0x5B,
		RENDER_TARGET_GODRAYS_ACCUMULATION = 0x5C,
		RENDER_TARGET_GODRAYS_RESOLVED = 0x5D,
		RENDER_TARGET_GODRAYS_RESOLVED_DEPTH = 0x5E,
		RENDER_TARGET_GODRAYS_FILTERED_0 = 0x5F,
		RENDER_TARGET_GODRAYS_FILTERED_1 = 0x60,
		RENDER_TARGET_GODRAYS_FILTERED_DEPTH_0 = 0x61,
		RENDER_TARGET_GODRAYS_FILTERED_DEPTH_1 = 0x62,
		RENDER_TARGET_MONITOR_SCREENSHOT = 0x63,

		RENDER_TARGET_COUNT
	};

	enum RenderTargetCubeMapMode : std::uint32_t
	{
		RENDER_TARGET_CUBEMAP_NONE = static_cast<std::underlying_type_t<RenderTargetCubeMapMode>>(-1),

		RENDER_TARGET_CUBEMAP_REFLECTIONS = 0x0,

		RENDER_TARGET_CUBEMAP_COUNT
	};

	enum DepthStencilTargetMode : std::uint32_t
	{
		DEPTH_STENCIL_TARGET_NONE = static_cast<std::underlying_type_t<DepthStencilTargetMode>>(-1),

		DEPTH_STENCIL_TARGET_FRAMEBUFFER = 0x0,
		DEPTH_STENCIL_TARGET_FRAMEBUFFER_COUNT = 0x1,

		DEPTH_STENCIL_TARGET_MAIN = 0x1,
		DEPTH_STENCIL_TARGET_MAIN_HALF_RES = 0x2,
		DEPTH_STENCIL_TARGET_PIPBOY = 0x3,
		DEPTH_STENCIL_TARGET_VATS = 0x4,
		DEPTH_STENCIL_TARGET_SHADOWMAP = 0x5,
		DEPTH_STENCIL_TARGET_SHADOWMAP_ARRAY = 0x6,
		DEPTH_STENCIL_CUBEMAP_REFLECTIONS = 0x7,
		DEPTH_STENCIL_TARGET_RAIN_OCCLUSIONMAP = 0x8,
		DEPTH_STENCIL_TARGET_VLS_SLICE_STENCIL = 0x9,
		DEPTH_STENCIL_TARGET_GODRAYS = 0xA,
		DEPTH_STENCIL_COMPANION_LOCAL_MAP = 0xB,

		DEPTH_STENCIL_COUNT
	};
}
