#pragma once

namespace RE
{
	enum hkDisplayGeometryType
	{
		HK_DISPLAY_RECTANGLE = 0,
		HK_DISPLAY_SPHERE,
		HK_DISPLAY_BOX,
		HK_DISPLAY_AABB,
		HK_DISPLAY_CONE,
		HK_DISPLAY_SEMICIRCLE,
		HK_DISPLAY_CONVEX,
		HK_DISPLAY_PLANE,
		HK_DISPLAY_CAPSULE,
		HK_DISPLAY_CYLINDER,
		HK_DISPLAY_TAPERED_CAPSULE,
		HK_DISPLAY_MESH,
		HK_DISPLAY_WIREFRAME
	};
}